version: '3.4'

services:
  web:
    build:
      context: .
    env_file:
      - .env
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
